Fetch javaGD sources if not available
git-svn-id: svn://svn.rforge.net/JavaGD/trunk@55 cd9d9a8b-87fc-4580-8bc7-ead42e10e920

diff --git a/mkdist b/mkdist
--- a/mkdist
+++ b/mkdist
@@ -30,6 +30,20 @@ find . -name CVS | xargs rm -rf
 find . -name \*~ | xargs rm -f
 
 if [ ! -e src/java/javaGD.jar ]; then
+    echo "Compiling javaGD Java sources"
+    if [ ! -e src/java/Makefile ]; then
+	rm -rf src/java
+	mkdir src/java 2> /dev/null
+	: ${JAVASRC=$SWD/../../../org/rosuda/javaGD}
+	if [ ! -e "$JAVASRC/GDInterface.java" ]; then
+	    echo "*** ERROR: cannot find javaGD sources in $JAVASRC ***"
+	    echo "Please set JAVASRC to the directory containing javaGD sources"
+	    exit 1
+	fi
+	cp "$JAVASRC/"*.java src/java/
+	cp "$JAVASRC/Makefile" src/java/
+    fi
+
     make -C src/java 'JFLAGS=-source 1.2 -target 1.2'
     if [ $? != 0 ]; then
 	exit 1
